name: ParticleUI
author: SigitGamers
version: 1.0
main: SigitGamersYT\Particle\Main
api: 4.0.0
commands:
  pui:
    usage: "/pui"
    description: "Open ParticleUI"
    permission: pui.cmd
permissions:
  pui.cmd:
    default: op
