name: ParticleUI
author: SigitGamers
version: 1.0
main: SigitGamersYT\Particle\Main
api: 4.0.0

commands:
  pui:
    description: "Open ParticleUI"
    permissions: pui.cmd
permission:
  pui.cmd:
    default: op
    description: ""
    
